'use client'

import { useState, useCallback } from 'react'
import Link from 'next/link'

type FAQItem = {
  q: string
  a: string | string[]
  /** Optional JSX to append after the answer paragraphs */
  extra?: React.ReactNode
}

type FAQSection = {
  id: string
  title: string
  items: FAQItem[]
}

const faqSections: FAQSection[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    items: [
      {
        q: 'What is Claude Cowork?',
        a: [
          'Cowork is Anthropic\'s collaborative AI workspace. Unlike ChatGPT, which gives you text responses, Cowork runs pre-built "skills" that produce finished work: formatted reports, analyzed data, draft emails, presentations.',
          'You describe what you need, drag in your files, and get results you can actually use. No prompt engineering required.',
        ],
      },
      {
        q: 'What\'s the Summit, Scout, Trekker model?',
        a: [
          'It\'s a simple framework for how AI actually gets adopted in a team or business.',
          'Summit (leadership) picks which problems to solve. Scouts (technical) build reusable AI skills using Claude Code. Trekkers (everyone else) run those skills daily in Cowork.',
          'Three roles, three tools, one system. Most people start as their own Summit and Scout, then scale from there.',
        ],
        extra: (
          <Link
            href="/how-it-works"
            className="inline-flex items-center gap-1.5 text-sm font-heading font-semibold transition-colors mt-1"
            style={{ color: '#D64C00' }}
          >
            Read the full SST breakdown
            <span>&#8594;</span>
          </Link>
        ),
      },
      {
        q: 'Do I need a Claude subscription? Which plan?',
        a: [
          'Yes. You need at least a Claude Pro subscription ($20/month from Anthropic). This gives you access to Cowork where you can run skills.',
          'If you\'re a Scout building skills with Claude Code, the Pro plan works too, though the Max plan gives you more usage for heavier building sessions.',
        ],
      },
      {
        q: 'I\'m not technical. Is this for me?',
        a: [
          'Absolutely. The whole point of the Trekker role is that you don\'t need to be technical. Someone else (a Scout) builds the skills. You just open Cowork, type a short prompt, drag in a file if needed, and get results.',
          'If you can attach a file to an email, you can use Cowork.',
        ],
      },
    ],
  },
  {
    id: 'demos',
    title: 'The Demos',
    items: [
      {
        q: 'Why are you giving me sample data? Can I use my own?',
        a: [
          'The sample data lets you test everything immediately without hunting for the right file format or worrying about sharing sensitive information.',
          'But yes, you can absolutely use your own data. Every demo that accepts a file will work with your real files too. The sample data is just there so you can see results in seconds.',
        ],
      },
      {
        q: 'Why are there hidden game levels?',
        a: 'Because business should be fun. This whole site is built as a game on purpose. There are hidden levels, secret worlds, and surprises tucked away. Finding them won\'t teach you anything extra, but it\'ll make you smile. That\'s reason enough.',
      },
      {
        q: 'Are the demo results real or scripted?',
        a: [
          'Every result was generated by AI. Nothing was hand-written or cherry-picked.',
          'That said, to keep the site fast and handle traffic, we show you pre-generated AI outputs rather than running a fresh AI call every time you click. The quality you see is the quality you get when you run these skills yourself in Cowork.',
        ],
      },
    ],
  },
  {
    id: 'safety',
    title: 'Safety & Privacy',
    items: [
      {
        q: 'Is my data safe when I send it to an AI?',
        a: [
          'When you use Cowork through your Claude subscription, your data is covered by Anthropic\'s privacy policy. Anthropic does not train its models on your conversations or files. Your data is processed to generate a response and that\'s it. It\'s not shared, sold, or used to improve the AI.',
          'Think of it like sending a document to an accountant, not posting it on social media.',
        ],
      },
      {
        q: 'Is it safe to connect real tools like Gmail and Google Calendar?',
        a: [
          'Yes, and many people do. Cowork can work with your email, calendar, documents, and more through official integrations.',
          'That said, if your company has policies about which tools can access corporate accounts, check with your IT team or manager first. Getting internal approval before connecting is always smart.',
        ],
      },
      {
        q: 'What if my company has policies about AI tools?',
        a: [
          'Talk to your IT team or compliance department first. Many companies now have AI usage policies, and that\'s a good thing.',
          'The good news: Anthropic offers enterprise plans with additional security controls if that\'s needed. Cowork is one of the more enterprise-friendly AI tools available, with clear data handling policies and no model training on your data.',
        ],
      },
    ],
  },
  {
    id: 'skills',
    title: 'Skills',
    items: [
      {
        q: 'What exactly is a "skill"?',
        a: [
          'A skill is a reusable AI instruction set. Instead of writing a new prompt every time, a skill packages the instructions, formatting, and logic into something you can run with one line.',
          'Think of it like a recipe: someone writes it once, and then anyone can follow it to get consistent results every time.',
        ],
      },
      {
        q: 'Can I build my own skills or do I need a developer?',
        a: [
          'You can build your own. If you\'re comfortable writing clear instructions (even in plain English), you can create skills using Claude Code. You don\'t need to be a programmer, but it helps to be systematic about what you want.',
          'The Ads to AI community teaches skill-building from scratch, starting with simple ones and working up to complex multi-step workflows.',
        ],
      },
    ],
  },
  {
    id: 'ads-to-ai',
    title: 'Ads to AI Community',
    items: [
      {
        q: 'What is the Ads to AI community?',
        a: [
          'Ads to AI is a membership community that teaches people how to integrate AI into their work, starting with practical tools and building toward running your business with AI.',
          'It started in the Google Ads world but has grown well beyond that. Members get access to ready-made skills, courses, live calls, and a community of people going through the same journey.',
        ],
      },
      {
        q: 'Who is the Ads to AI community for?',
        a: [
          'Business owners, marketers, agency teams, freelancers. Anyone who wants to use AI to get real work done, not just chat with a bot.',
          'You don\'t need to be a Google Ads professional. Many members come from completely different backgrounds. If you\'re curious about AI but tired of hype and want practical, working systems, it\'s for you.',
        ],
      },
      {
        q: 'What do I get as a member?',
        a: [
          'A library of pre-built skills you can use immediately. Courses that teach you to build your own. Weekly live calls with real problem-solving. A community of people sharing what works.',
          'And the brain system: a personal AI infrastructure that connects to your email, calendar, and files. New skills and updates ship regularly.',
        ],
      },
    ],
  },
  {
    id: 'about',
    title: 'About',
    items: [
      {
        q: 'Who built this?',
        a: [
          'Mike Rhodes, founder of ads2ai.com. Mike has been in the digital marketing world for 20 years and has been building AI tools and teaching since 2023.',
          'This demo site, the skills, and the community are all built by one person using the same AI tools you see here. That\'s kind of the point.',
        ],
      },
    ],
  },
]

/** Build a flat key for each question: "sectionId:questionIndex" */
function itemKey(sectionId: string, idx: number) {
  return `${sectionId}:${idx}`
}

function FAQRow({
  item,
  itemKey: key,
  isLast,
  isOpen,
  onToggle,
}: {
  item: FAQItem
  itemKey: string
  isLast: boolean
  isOpen: boolean
  onToggle: () => void
}) {
  const paragraphs = Array.isArray(item.a) ? item.a : [item.a]

  return (
    <div data-faq-key={key} className={!isLast ? 'border-b border-[var(--color-border)]' : ''}>
      <button
        onClick={onToggle}
        className="w-full flex items-center gap-3 px-5 sm:px-6 py-3 hover:bg-[var(--color-cream)] transition-colors group text-left"
      >
        <span
          className="flex-shrink-0 w-4 h-4 flex items-center justify-center text-[var(--color-faint)] transition-transform"
          style={{ transform: isOpen ? 'rotate(90deg)' : 'rotate(0deg)' }}
        >
          <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <polyline points="3,1 7,5 3,9" />
          </svg>
        </span>
        <span className="text-sm text-[var(--color-ink)] group-hover:text-[var(--color-brand-orange)] transition-colors">
          {item.q}
        </span>
      </button>
      {isOpen && (
        <div className="px-5 sm:px-6 pb-4 pl-12 sm:pl-[3.25rem] space-y-3">
          {paragraphs.map((p, i) => (
            <p key={i} className="text-sm text-[var(--color-muted)] leading-relaxed">
              {p}
            </p>
          ))}
          {item.extra}
        </div>
      )}
    </div>
  )
}

export default function FAQPage() {
  const [openKey, setOpenKey] = useState<string | null>(null)

  const handleToggle = useCallback((key: string) => {
    const next = openKey === key ? null : key
    setOpenKey(next)
    if (next) {
      requestAnimationFrame(() => {
        const el = document.querySelector(`[data-faq-key="${next}"]`)
        if (el) {
          const rect = el.getBoundingClientRect()
          if (rect.top < 56 || rect.bottom > window.innerHeight) {
            el.scrollIntoView({ behavior: 'smooth', block: 'start' })
          }
        }
      })
    }
  }, [openKey])

  // Figure out which section the open question belongs to
  const activeSection = openKey ? openKey.split(':')[0] : null

  return (
    <div className="min-h-[calc(100vh-3.5rem)] flex max-w-6xl mx-auto">

      {/* Sidebar */}
      <aside className="hidden lg:block w-64 shrink-0 border-r border-[var(--color-border)] py-8 pr-4 pl-6">
        <div className="sticky top-[3.5rem] max-h-[calc(100vh-3.5rem)] overflow-y-auto pb-8">
          <Link
            href="/"
            className="text-xs font-heading font-semibold text-[var(--color-muted)] hover:text-[var(--color-ink)] transition-colors mb-6 block"
          >
            &#8592; Back to demos
          </Link>
          <nav className="space-y-5">
            {faqSections.map((section) => (
              <div key={section.id}>
                <p className={`text-[10px] font-bold uppercase tracking-widest mb-1.5 font-heading ${
                  activeSection === section.id
                    ? 'text-[var(--color-brand-orange)]'
                    : 'text-[var(--color-brand-orange)]'
                }`}>
                  {section.title}
                </p>
                <ul className="space-y-0.5">
                  {section.items.map((item, idx) => {
                    const key = itemKey(section.id, idx)
                    const isCurrent = openKey === key
                    return (
                      <li key={key}>
                        <button
                          onClick={() => handleToggle(key)}
                          className={`block text-left text-xs py-1 transition-colors w-full ${
                            isCurrent
                              ? 'text-[var(--color-ink)] font-semibold border-l-2 border-[var(--color-brand-orange)] pl-2 -ml-[2px]'
                              : 'text-[var(--color-muted)] hover:text-[var(--color-ink)]'
                          }`}
                        >
                          {item.q}
                        </button>
                      </li>
                    )
                  })}
                </ul>
              </div>
            ))}
          </nav>

          {/* Cross-links */}
          <div className="mt-8 pt-6 border-t border-[var(--color-border)]">
            <Link
              href="/how-it-works"
              className="block text-xs text-[var(--color-muted)] hover:text-[var(--color-ink)] transition-colors font-heading"
            >
              How It Works (SST) &#8594;
            </Link>
            <Link
              href="/course"
              className="block text-xs text-[var(--color-muted)] hover:text-[var(--color-ink)] transition-colors font-heading mt-2"
            >
              Free Cowork Course &#8594;
            </Link>
          </div>
        </div>
      </aside>

      {/* Main content */}
      <div className="flex-1 min-w-0 px-4 sm:px-6 lg:px-10 py-8 sm:py-12">

        {/* Header */}
        <div className="text-center mb-12">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--color-brand-orange)] mb-3 font-heading">
            FAQ
          </p>
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold leading-[1.1] mb-4 font-heading text-[var(--color-ink)]">
            Frequently Asked Questions
          </h1>
          <p className="text-base text-[var(--color-muted)] max-w-lg mx-auto leading-relaxed">
            Everything you need to know about the demos, Cowork, and the Ads to AI community.
          </p>
        </div>

        {/* FAQ cards */}
        <div className="space-y-6 max-w-3xl mx-auto">
          {faqSections.map((section) => (
            <div
              key={section.id}
              className="border rounded-[2px] overflow-hidden bg-white border-[var(--color-border)]"
            >
              <div
                className="px-5 sm:px-6 py-4 border-b border-[var(--color-border)]"
                style={{ borderLeft: '3px solid var(--color-brand-orange)' }}
              >
                <h2 className="text-lg font-bold font-heading text-[var(--color-ink)]">
                  {section.title}
                </h2>
              </div>

              <div>
                {section.items.map((item, idx) => {
                  const key = itemKey(section.id, idx)
                  return (
                    <FAQRow
                      key={key}
                      item={item}
                      itemKey={key}
                      isLast={idx === section.items.length - 1}
                      isOpen={openKey === key}
                      onToggle={() => handleToggle(key)}
                    />
                  )
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Bottom links (visible on mobile where sidebar is hidden) */}
        <div className="flex flex-col sm:flex-row gap-3 justify-center mt-12 lg:hidden">
          <Link
            href="/how-it-works"
            className="inline-flex items-center justify-center px-6 py-3 text-sm font-semibold font-heading text-white rounded-[2px] transition-colors"
            style={{ backgroundColor: '#D64C00' }}
          >
            How It Works (SST)
          </Link>
          <Link
            href="/"
            className="inline-flex items-center justify-center px-6 py-3 text-sm font-semibold font-heading rounded-[2px] transition-colors border border-[var(--color-border)] text-[var(--color-muted)] hover:text-[var(--color-ink)] hover:border-[var(--color-ink)]"
          >
            &#8592; Back to demos
          </Link>
        </div>

      </div>
    </div>
  )
}
